version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: akaunting-app
    container_name: akaunting-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - akaunting-network
    environment:
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - APP_NAME=Akaunting
      - APP_ENV=production
      - APP_LOCALE=en-GB
      - APP_INSTALLED=false
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=akaunting
      - DB_USERNAME=abdo
      - DB_PASSWORD=1234
      - CACHE_DRIVER=file
      - LOG_CHANNEL=stack

  nginx:
    image: nginx:latest
    container_name: akaunting-nginx
    restart: unless-stopped
    ports:
      - "8082:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www  
    networks:
      - akaunting-network

  db:
    image: mysql:8.0
    container_name: akaunting-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: akaunting
      MYSQL_USER: abdo
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - akaunting-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - akaunting-network

volumes:
  db_data:

networks:
  akaunting-network:
    driver: bridge

